MuseumArt_App/config/routes.rb
Rails.application.routes.draw do

  root 'paintings#index'

  resources :paintings
  resources :museums
  resources :artists

end

MuseumArt_App/app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :paintings
	has_many :museums, through: :paintings
end

MuseumArt_App/app/models/museum.rb
class Museum < ActiveRecord::Base
	has_many :paintings
	has_many :artists, through: :paintings
end

MuseumArt_App/app/models/painting.rb
class Painting < ActiveRecord::Base
#	validates :title, :date, :artist, presence: true
#	validates :date, numericality: {greater_than_or_equal_to: 0, only_integer: true }

#	belongs_to :artist
#	belongs_to :museum

	def self.search_for(query)
		where('title LIKE :query', :query => "%#{query}%")
	end
end

MuseumArt_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

MuseumArt_App/app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  before_action :load_museum, only: [:edit, :show, :update]

  def index
  	@museums = Museum.all
  end

  def new
  	@museum = Museum.new
  end

  def show
  end

  def create
  	@museum = Museum.new(safe_museum_params)
  	if @museum.save
  		redirect_to @museum
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
  end

  private

  def load_museum
  	@museum = Museum.find(params[:id])
  rescue ActiveRecord::RecordNotFound
  	flash.now[:notice] = "Invalid Museum ID #{params[:id]}"
  	redirect_to root_path
  end

  def safe_museum_params
  	params.require(:museum).permit(:name, :city)
  end
end

MuseumArt_App/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  #before_action :load_painting, only: [:edit, :show, :update]
  
  def index
    @paintings = params[:q] ? Painting.search_for(params[:q]) : Painting.all 
  end

  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.new(safe_painting_params)
    if @painting.save
      redirect_to @painting
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @painting.update(safe_painting_params)
      redirect_to @painting
    else
      render 'edit'
    end
  end

  def show
  end

  private

  def safe_painting_params
    params.require(:painting).permit(:title, :date, :artist, :image, :museum_id)
  end

  def load_painting
    @painting = Painting.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash.now[:notice] = "Invalid Painting ID #{params[:id]}"
    redirect_to root_path
  end
end

MuseumArt_App/app/helpers/application_helper.rb
module ApplicationHelper
end

MuseumArt_App/app/helpers/museums_helper.rb
module MuseumsHelper
end

MuseumArt_App/app/helpers/paintings_helper.rb
module PaintingsHelper
end

MuseumArt_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MuseumArtApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
	<body>
	  <div class="container">
		  <ul class="nav nav-tabs">
			 <li><%= link_to "All Museums", museums_path %></li>
			 <li><%= link_to "All Paintings", paintings_path %></li>
			 <li><%= link_to "Add New Painting", new_painting_path %></li>
		  </ul>
		<div class="container">
		  <div id="container">
		   <%= yield %>
		  </div>
		</div>
	  </div>

	</body>
</html>

MuseumArt_App/app/views/museums/_form.html.erb
<% if @museum.errors.any? %>
	<h2>There was a problems saving your museum.</h2>
	<ul>
	  <% @museum.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
	</ul>
	<% end %>

<%= form_for @museum do |f| %>
  <fieldset>
  	<div class='fields'>
  	  <%= f.label :name %>
  	  <%= f.text_field :name %>
  	</div>
  	<div class='fields'>
  	  <%= f.label :city %>
  	  <%= f.text_field :city %>
  	</div>
  </fieldset>
  <%= f.submit %>
<% end %>

<br/>

MuseumArt_App/app/views/museums/edit.html.erb
<h1>Edit Museum</h1>
<%= render 'form' %>

MuseumArt_App/app/views/museums/index.html.erb
<h1>Museums Art App</h1>
<h2>Museums</h2>

<h3><%= link_to "Add New Museum", new_museum_path %> <%= link_to "Add New Painting", new_painting_path %></h3>

<% @museums.each do |museum| %>
	<hr/>
	<section>
	  <h3><%= link_to museum.name, museum %></h3>
	  <p><%= museum.city %></p>
	</section>
<% end %>

MuseumArt_App/app/views/museums/new.html.erb
<h1>Add a New Museum</h1>
<%= render 'form' %>

MuseumArt_App/app/views/museums/show.html.erb
<h1><%= @museum.name %></h1>
<p><%= @museum.city %></p>
<b><%= link_to "Add New Museum", new_museum_path %></b><br>
<b><%= link_to "Museum Art App Home", root_path %></b>

MuseumArt_App/app/views/paintings/_form.html.erb
<% if @painting.errors.any? %>
  <h2>There was a problem saving your painting or image.</h2>
  <ul>
  	<% @painting.errors.full_messages.each do |msg| %>
  		<li><%= msg %></li>
  	<% end %>	
  </ul>
<% end %>

<%= form_for @painting do |f| %>
  <fieldset>
  	<div class='fields'>
  	   <%= f.label :title %>
  	   <%= f.text_field :title %>
  	</div>

  	<div class='fields'>
  	   <%= f.label :year %>
  	   <%= f.text_field :date %>
  	</div>

  	<div class='fields'>
  	   <%= f.label :artist %>
  	   <%= f.text_field :artist %>
  	</div>

  	<div class='fields'>
  	   <%= f.label :image %>
  	   <%= f.text_field :image %>
  	</div>
  	</div class='fields'>
  		<%= f.label :museum %>
  		<%= f.select :museum_id, Museum.all.collect {|museum| [museum.name, museum.id]} %>
  	<div>

  </fieldset>
  <%= f.submit %>
<% end %>
<br/>

MuseumArt_App/app/views/paintings/edit.html.erb
<h1>Edit the Painting</h1>
<%= image_tag @painting.image %>
<%= render 'form' %>

MuseumArt_App/app/views/paintings/index.html.erb
<h1>Museum Art</h1>

<p>View inventory below or search by title here.</p>
<%= form_tag "/", method: :get do %>
	<%= text_field_tag :q, params[:q] %>
	<%= submit_tag "Search" %>
<% end %>
<br/><hr/>
<strong>Inventory</strong>
<% if @paintings.any? %>

	<% @paintings.each do |painting| %>
	  <section>
	  	<h3><b>Title</b>: <%= link_to painting.title, paintings_path %></h3>
	  	<%= image_tag painting.image %>
	  	<p><b>Artist</b>: <%= painting.artist %></p>
	  	<p><b>Year</b>: <%= painting.date %></p>
	  	<p><b>Museum</b>: <%= link_to painting.museum, museums_path %></p>
	  	<hr>
	  </section>
	<% end %> 

<% else %>

<h3>Sorry the painting you search for is not in the database.</h3>

<% end %>

MuseumArt_App/app/views/paintings/new.html.erb
<h1>Add a New Painting or Image</h1>
<%= render 'form' %>

MuseumArt_App/app/views/paintings/show.html.erb
<h1>Show Paintings and Images in Collection</h1>
<h1><%= @painting.title %></h1>
	<p><strong>Artist</strong>: <%= @painting.artist %></p>
	<p><strong>Year</strong>: <%= @painting.date %></p>
	<p><strong>Museum</strong>: <%= @painting.museum %></p>
	<%= image_tag @painting.image %>
<br/>
<%= link_to "Edit this painting.", edit_painting_path(@painting) %>	
<br/><br/>